-- BiSGearCheck Data_WoWSims.lua
-- WoWSims TBC simulation-derived BiS data
-- Auto-generated by scripts/extract_wowsims.py

BiSGearCheckDB_WoWSims = {}

BiSGearCheckDB_WoWSims["DruidBalance"] = {
    class = "DRUID",
    spec = "Balance",
    slots = {
        ["Head"] = { 29093, 30233 },
        ["Neck"] = { 28762, 30015 },
        ["Shoulders"] = { 29095, 30235 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 21848, 30231 },
        ["Wrist"] = { 24250, 29918 },
        ["Hands"] = { 21847, 30232 },
        ["Waist"] = { 21846, 30038 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517, 30067 },
        ["Rings"] = { 28753, 28793, 29302 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28770, 29988 },
        ["Offhand"] = { 29271, 32387 },
        ["Ranged"] = { 27518 },
    }
}

BiSGearCheckDB_WoWSims["DruidFeralDPS"] = {
    class = "DRUID",
    spec = "Feral DPS",
    slots = {
        ["Head"] = { 8345 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 29100 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29096 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 28506 },
        ["Waist"] = { 28750 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28649, 30834 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28658 },
        ["Offhand"] = { 29390 },
    }
}

BiSGearCheckDB_WoWSims["DruidFeralTank"] = {
    class = "DRUID",
    spec = "Feral Tank",
    slots = {
        ["Head"] = { 29098 },
        ["Neck"] = { 28509 },
        ["Shoulders"] = { 29100 },
        ["Back"] = { 28660 },
        ["Chest"] = { 29096 },
        ["Wrist"] = { 28978 },
        ["Hands"] = { 29097 },
        ["Waist"] = { 28986 },
        ["Legs"] = { 29099 },
        ["Feet"] = { 30674 },
        ["Rings"] = { 29279, 28792 },
        ["Trinkets"] = { 28830, 23836 },
        ["Main Hand"] = { 28476 },
        ["Offhand"] = { 23198 },
    }
}

BiSGearCheckDB_WoWSims["DruidRestoration"] = {
    class = "DRUID",
    spec = "Restoration",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["HunterBM"] = {
    class = "HUNTER",
    spec = "Beast Mastery",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 24259 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27474 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 30739 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28435 },
        ["Offhand"] = { 28772 },
    }
}

BiSGearCheckDB_WoWSims["HunterMM"] = {
    class = "HUNTER",
    spec = "Marksmanship",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 24259 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27474 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 30739 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28435 },
        ["Offhand"] = { 28772 },
    }
}

BiSGearCheckDB_WoWSims["HunterSV"] = {
    class = "HUNTER",
    spec = "Survival",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 24259 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27474 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 30739 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28435 },
        ["Offhand"] = { 28772 },
    }
}

BiSGearCheckDB_WoWSims["MageArcane"] = {
    class = "MAGE",
    spec = "Arcane",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28134 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766 },
        ["Chest"] = { 21848 },
        ["Wrist"] = { 28411 },
        ["Hands"] = { 21847 },
        ["Waist"] = { 21846 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28793, 29172 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 29270 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["MageFire"] = {
    class = "MAGE",
    spec = "Fire",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28134 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766 },
        ["Chest"] = { 21848 },
        ["Wrist"] = { 28411 },
        ["Hands"] = { 21847 },
        ["Waist"] = { 21846 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28793, 29172 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 29270 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["MageFrost"] = {
    class = "MAGE",
    spec = "Frost",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28134 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766 },
        ["Chest"] = { 21848 },
        ["Wrist"] = { 28411 },
        ["Hands"] = { 21847 },
        ["Waist"] = { 21846 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28793, 29172 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 29270 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["PaladinHoly"] = {
    class = "PALADIN",
    spec = "Holy",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["PaladinProtection"] = {
    class = "PALADIN",
    spec = "Protection",
    slots = {
        ["Head"] = { 32521 },
        ["Neck"] = { 32362 },
        ["Shoulders"] = { 30998 },
        ["Back"] = { 33593 },
        ["Chest"] = { 30991 },
        ["Wrist"] = { 32232 },
        ["Hands"] = { 30985 },
        ["Waist"] = { 32342 },
        ["Legs"] = { 30995 },
        ["Feet"] = { 32245 },
        ["Rings"] = { 32261, 29172 },
        ["Trinkets"] = { 31858, 33829 },
        ["Main Hand"] = { 30910 },
        ["Offhand"] = { 32375 },
        ["Ranged"] = { 33504 },
    }
}

BiSGearCheckDB_WoWSims["PaladinRetribution"] = {
    class = "PALADIN",
    spec = "Retribution",
    slots = {
        ["Head"] = { 32235 },
        ["Neck"] = { 30022 },
        ["Shoulders"] = { 30055 },
        ["Back"] = { 33590 },
        ["Chest"] = { 30905 },
        ["Wrist"] = { 32574 },
        ["Hands"] = { 29947 },
        ["Waist"] = { 30106 },
        ["Legs"] = { 30900 },
        ["Feet"] = { 32366 },
        ["Rings"] = { 32526, 30834 },
        ["Trinkets"] = { 33831, 28830 },
        ["Main Hand"] = { 32332 },
        ["Offhand"] = { 27484 },
    }
}

BiSGearCheckDB_WoWSims["PriestHoly"] = {
    class = "PRIEST",
    spec = "Holy",
    slots = {
        ["Head"] = { 24266, 32525 },
        ["Neck"] = { 28530, 32349 },
        ["Shoulders"] = { 29060, 31070 },
        ["Back"] = { 28766, 32524 },
        ["Chest"] = { 29056, 30107 },
        ["Wrist"] = { 24250, 32586 },
        ["Hands"] = { 30725, 31061 },
        ["Waist"] = { 24256, 30038 },
        ["Legs"] = { 30734, 30916 },
        ["Feet"] = { 28517, 32239 },
        ["Rings"] = { 28793, 29172, 32527, 32247 },
        ["Trinkets"] = { 27683, 29370, 32483 },
        ["Main Hand"] = { 30723, 32374 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 29982 },
    }
}

BiSGearCheckDB_WoWSims["PriestShadow"] = {
    class = "PRIEST",
    spec = "Shadow",
    slots = {
        ["Head"] = { 24266, 31064 },
        ["Neck"] = { 30666 },
        ["Shoulders"] = { 21869, 31070 },
        ["Back"] = { 28570, 32590 },
        ["Chest"] = { 21871, 31065 },
        ["Wrist"] = { 24250, 32586 },
        ["Hands"] = { 28507, 31061 },
        ["Waist"] = { 28799, 32256 },
        ["Legs"] = { 24262, 30916 },
        ["Feet"] = { 21870, 32239 },
        ["Rings"] = { 29352, 28793, 32527 },
        ["Trinkets"] = { 28789, 29370, 32483 },
        ["Main Hand"] = { 28770, 32374 },
        ["Offhand"] = { 29272, 29982 },
        ["Ranged"] = { 29350 },
    }
}

BiSGearCheckDB_WoWSims["RogueAssassination"] = {
    class = "ROGUE",
    spec = "Assassination",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["RogueCombat"] = {
    class = "ROGUE",
    spec = "Combat",
    slots = {
        ["Head"] = { 29044 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27797 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29045 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27531 },
        ["Waist"] = { 29247 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28649 },
        ["Trinkets"] = { 29383, 28830 },
        ["Main Hand"] = { 28729, 28768 },
        ["Offhand"] = { 28189, 29182 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_WoWSims["RogueSubtlety"] = {
    class = "ROGUE",
    spec = "Subtlety",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["ShamanElemental"] = {
    class = "SHAMAN",
    spec = "Elemental",
    slots = {
        ["Head"] = { 29035 },
        ["Neck"] = { 28762 },
        ["Shoulders"] = { 29037 },
        ["Back"] = { 28797 },
        ["Chest"] = { 29519 },
        ["Wrist"] = { 29521 },
        ["Hands"] = { 28780 },
        ["Waist"] = { 29520 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 30667, 28753 },
        ["Trinkets"] = { 29370, 28785 },
        ["Main Hand"] = { 28770 },
        ["Offhand"] = { 29273 },
        ["Ranged"] = { 28248 },
    }
}

BiSGearCheckDB_WoWSims["ShamanEnhancement"] = {
    class = "SHAMAN",
    spec = "Enhancement",
    slots = {
        ["Head"] = { 30190 },
        ["Neck"] = { 30017 },
        ["Shoulders"] = { 30055 },
        ["Back"] = { 29994 },
        ["Chest"] = { 30185 },
        ["Wrist"] = { 30091 },
        ["Hands"] = { 30189 },
        ["Waist"] = { 30106 },
        ["Legs"] = { 30192 },
        ["Feet"] = { 30039 },
        ["Rings"] = { 29997, 30052 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 32944 },
        ["Offhand"] = { 29996 },
        ["Ranged"] = { 27815 },
    }
}

BiSGearCheckDB_WoWSims["ShamanRestoration"] = {
    class = "SHAMAN",
    spec = "Restoration",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["WarlockAffliction"] = {
    class = "WARLOCK",
    spec = "Affliction",
    slots = {
        ["Head"] = { 31051 },
        ["Neck"] = { 33281 },
        ["Shoulders"] = { 31054 },
        ["Back"] = { 32524 },
        ["Chest"] = { 30107 },
        ["Wrist"] = { 32586 },
        ["Hands"] = { 31050 },
        ["Waist"] = { 30888 },
        ["Legs"] = { 31053 },
        ["Feet"] = { 32239 },
        ["Rings"] = { 32527, 33497 },
        ["Trinkets"] = { 32483, 33829 },
        ["Main Hand"] = { 32374 },
        ["Ranged"] = { 33192 },
    }
}

BiSGearCheckDB_WoWSims["WarlockDemonology"] = {
    class = "WARLOCK",
    spec = "Demonology",
    slots = {
        ["Head"] = { 31051 },
        ["Neck"] = { 33281 },
        ["Shoulders"] = { 31054 },
        ["Back"] = { 32524 },
        ["Chest"] = { 30107 },
        ["Wrist"] = { 32586 },
        ["Hands"] = { 31050 },
        ["Waist"] = { 30888 },
        ["Legs"] = { 31053 },
        ["Feet"] = { 32239 },
        ["Rings"] = { 32527, 33497 },
        ["Trinkets"] = { 32483, 33829 },
        ["Main Hand"] = { 32374 },
        ["Ranged"] = { 33192 },
    }
}

BiSGearCheckDB_WoWSims["WarlockDestruction"] = {
    class = "WARLOCK",
    spec = "Destruction",
    slots = {
        ["Head"] = { 31051 },
        ["Neck"] = { 33281 },
        ["Shoulders"] = { 31054 },
        ["Back"] = { 32524 },
        ["Chest"] = { 30107 },
        ["Wrist"] = { 32586 },
        ["Hands"] = { 31050 },
        ["Waist"] = { 30888 },
        ["Legs"] = { 31053 },
        ["Feet"] = { 32239 },
        ["Rings"] = { 32527, 33497 },
        ["Trinkets"] = { 32483, 33829 },
        ["Main Hand"] = { 32374 },
        ["Ranged"] = { 33192 },
    }
}

BiSGearCheckDB_WoWSims["WarriorArms"] = {
    class = "WARRIOR",
    spec = "Arms",
    slots = {
        ["Head"] = { 29021 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 24259 },
        ["Chest"] = { 29019 },
        ["Wrist"] = { 28795 },
        ["Hands"] = { 28824 },
        ["Waist"] = { 28779 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28608 },
        ["Rings"] = { 28757, 30834 },
        ["Trinkets"] = { 29383, 28830 },
        ["Main Hand"] = { 28438 },
        ["Offhand"] = { 28729 },
        ["Ranged"] = { 30279 },
    }
}

BiSGearCheckDB_WoWSims["WarriorFury"] = {
    class = "WARRIOR",
    spec = "Fury",
    slots = {
        ["Head"] = { 29021 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 24259 },
        ["Chest"] = { 29019 },
        ["Wrist"] = { 28795 },
        ["Hands"] = { 28824 },
        ["Waist"] = { 28779 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28608 },
        ["Rings"] = { 28757, 30834 },
        ["Trinkets"] = { 29383, 28830 },
        ["Main Hand"] = { 28438 },
        ["Offhand"] = { 28729 },
        ["Ranged"] = { 30279 },
    }
}

BiSGearCheckDB_WoWSims["WarriorProtection"] = {
    class = "WARRIOR",
    spec = "Protection",
    slots = {
        ["Head"] = { 29011 },
        ["Neck"] = { 28244 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29012 },
        ["Wrist"] = { 28996 },
        ["Hands"] = { 30644 },
        ["Waist"] = { 28995 },
        ["Legs"] = { 28621 },
        ["Feet"] = { 28747 },
        ["Rings"] = { 30834, 29279 },
        ["Trinkets"] = { 28121, 29387 },
        ["Main Hand"] = { 28749 },
        ["Offhand"] = { 28825 },
        ["Ranged"] = { 28826 },
    }
}

