-- BiSGearCheck Data_TMB.lua
-- ThatsMyBis top wishlisted items (community aggregate data)
-- Auto-generated by scripts/scrape_tmb.py + assign_slots.py

BiSGearCheckDB_TMB = {}

BiSGearCheckDB_TMB["DruidBalance"] = {
    class = "DRUID",
    spec = "Balance",
    slots = {
        ["Head"] = { 29093 },
        ["Neck"] = { 28530, 28762 },
        ["Shoulders"] = { 29095 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 29091 },
        ["Hands"] = { 28507, 28780 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 28594, 28591, 30912 },
        ["Feet"] = { 28517, 28585 },
        ["Rings"] = { 28753, 32385, 28793 },
        ["Trinkets"] = { 28789, 29370, 27683 },
        ["Main Hand"] = { 28770, 28771, 32500, 30108 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 27518 },
    }
}

BiSGearCheckDB_TMB["DruidFeralDPS"] = {
    class = "DRUID",
    spec = "Feral DPS",
    slots = {
        ["Head"] = { 29098 },
        ["Neck"] = { 28509, 28609 },
        ["Shoulders"] = { 29100, 29089 },
        ["Back"] = { 28660, 28672, 28765 },
        ["Chest"] = { 29096, 29087 },
        ["Hands"] = { 30644, 28506, 29097, 28521 },
        ["Waist"] = { 28828, 28750, 28655 },
        ["Legs"] = { 28741, 29099, 28591 },
        ["Feet"] = { 28545, 30674, 28752 },
        ["Rings"] = { 32385, 28649, 28792, 28763 },
        ["Trinkets"] = { 28830, 28579, 28823, 28590 },
        ["Main Hand"] = { 28658, 28771 },
        ["Offhand"] = { 28728 },
        ["Twohand"] = { 28658 },
    }
}

BiSGearCheckDB_TMB["DruidFeralTank"] = {
    class = "DRUID",
    spec = "Feral Tank",
    slots = {
        ["Head"] = { 29098, 29093, 28744 },
        ["Neck"] = { 28509, 28530 },
        ["Shoulders"] = { 29100, 29095 },
        ["Back"] = { 28660, 28672, 28766 },
        ["Chest"] = { 29096, 29091 },
        ["Hands"] = { 30644, 29097 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 29099, 28741 },
        ["Feet"] = { 30674, 28545, 28517 },
        ["Rings"] = { 32385, 28792, 28649, 28753 },
        ["Trinkets"] = { 28830, 28579, 28789 },
        ["Main Hand"] = { 28658, 28770 },
        ["Offhand"] = { 23198, 28734 },
        ["Twohand"] = { 28658 },
        ["Ranged"] = { 23198 },
    }
}

BiSGearCheckDB_TMB["DruidRestoration"] = {
    class = "DRUID",
    spec = "Restoration",
    slots = {
        ["Head"] = { 29086, 28803, 29098 },
        ["Neck"] = { 28822, 28609 },
        ["Shoulders"] = { 29089, 29100 },
        ["Back"] = { 28765, 28672 },
        ["Chest"] = { 29087, 29096 },
        ["Wrist"] = { 28511 },
        ["Hands"] = { 28521, 29097 },
        ["Waist"] = { 28655 },
        ["Legs"] = { 28591, 29099 },
        ["Feet"] = { 28752 },
        ["Rings"] = { 28763, 32385, 28790 },
        ["Trinkets"] = { 29376, 28590, 28823, 28830 },
        ["Main Hand"] = { 28771, 28782, 28658 },
        ["Twohand"] = { 28782, 28658 },
        ["Ranged"] = { 27886 },
    }
}

BiSGearCheckDB_TMB["HunterBM"] = {
    class = "HUNTER",
    spec = "Beast Mastery",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 28509, 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 28672, 28777, 24259 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27474 },
        ["Waist"] = { 28828, 28750 },
        ["Legs"] = { 28741, 30739 },
        ["Feet"] = { 28545, 28746 },
        ["Rings"] = { 28757, 32385, 28649, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28587, 28572 },
        ["Offhand"] = { 28772, 28572 },
        ["Twohand"] = { 28587 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB["HunterMM"] = {
    class = "HUNTER",
    spec = "Marksmanship",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 28509 },
        ["Shoulders"] = { 27801 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27474 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 32385, 28649, 23067 },
        ["Trinkets"] = { 28830 },
        ["Main Hand"] = { 28587, 28572 },
        ["Offhand"] = { 28772, 28572 },
        ["Twohand"] = { 28587 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB["HunterSV"] = {
    class = "HUNTER",
    spec = "Survival",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 28343, 28674 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 28672 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 30686 },
        ["Hands"] = { 27474, 28506 },
        ["Waist"] = { 28750, 28828, 30677 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545, 28746, 30682 },
        ["Rings"] = { 32385, 28791, 28649, 28757 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28587, 28572 },
        ["Offhand"] = { 28772, 28572 },
        ["Twohand"] = { 28587 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB["MageArcane"] = {
    class = "MAGE",
    spec = "Arcane",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28762, 28530 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28797, 28766 },
        ["Hands"] = { 28780 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 29078, 28594 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 32385, 28793, 28753, 29287 },
        ["Trinkets"] = { 28785, 28789, 29370 },
        ["Main Hand"] = { 28802, 28770 },
        ["Ranged"] = { 28783, 28673 },
    }
}

BiSGearCheckDB_TMB["MageFire"] = {
    class = "MAGE",
    spec = "Fire",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28530, 28762 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766, 28797 },
        ["Wrist"] = { 28515 },
        ["Hands"] = { 28780 },
        ["Legs"] = { 29078, 28594 },
        ["Feet"] = { 28517, 28585 },
        ["Rings"] = { 28793, 28753, 32385 },
        ["Trinkets"] = { 29370, 28785 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 28783 },
    }
}

BiSGearCheckDB_TMB["MageFrost"] = {
    class = "MAGE",
    spec = "Frost",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28762, 28530 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766, 28797 },
        ["Wrist"] = { 28515 },
        ["Hands"] = { 28780, 29080, 28507 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 29078 },
        ["Feet"] = { 28517, 28585 },
        ["Rings"] = { 28753, 28793, 32385 },
        ["Trinkets"] = { 28785 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28783, 28673 },
    }
}

BiSGearCheckDB_TMB["PaladinHoly"] = {
    class = "PALADIN",
    spec = "Holy",
    slots = {
        ["Head"] = { 29061 },
        ["Neck"] = { 28822, 28609, 28516 },
        ["Shoulders"] = { 29064 },
        ["Back"] = { 28765 },
        ["Chest"] = { 29062 },
        ["Wrist"] = { 28512 },
        ["Hands"] = { 28505, 29065 },
        ["Waist"] = { 28733, 28566 },
        ["Legs"] = { 28748 },
        ["Feet"] = { 28569, 28752, 28747 },
        ["Rings"] = { 28790, 32385, 28763 },
        ["Trinkets"] = { 28590, 28727, 29376, 28789, 28528 },
        ["Main Hand"] = { 28771, 28802 },
        ["Offhand"] = { 29458, 28825, 29268 },
        ["Ranged"] = { 28592 },
    }
}

BiSGearCheckDB_TMB["PaladinProtection"] = {
    class = "PALADIN",
    spec = "Protection",
    slots = {
        ["Head"] = { 29068 },
        ["Neck"] = { 28516 },
        ["Shoulders"] = { 29070 },
        ["Back"] = { 27804 },
        ["Chest"] = { 29066 },
        ["Wrist"] = { 28502 },
        ["Hands"] = { 28518, 29067 },
        ["Waist"] = { 28566 },
        ["Legs"] = { 29069, 28621 },
        ["Feet"] = { 30641 },
        ["Rings"] = { 32385, 28675, 28793 },
        ["Trinkets"] = { 28789, 28528 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 28825 },
        ["Ranged"] = { 29388 },
    }
}

BiSGearCheckDB_TMB["PaladinRetribution"] = {
    class = "PALADIN",
    spec = "Retribution",
    slots = {
        ["Head"] = { 29073 },
        ["Neck"] = { 28745, 28509 },
        ["Shoulders"] = { 29075 },
        ["Back"] = { 28777, 28672 },
        ["Chest"] = { 29071 },
        ["Wrist"] = { 28795 },
        ["Hands"] = { 30644 },
        ["Waist"] = { 28779 },
        ["Feet"] = { 28608, 28545 },
        ["Rings"] = { 28757, 28730, 30834 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28800, 28773 },
        ["Offhand"] = { 28825 },
        ["Twohand"] = { 28773 },
        ["Ranged"] = { 27484 },
    }
}

BiSGearCheckDB_TMB["PriestHoly"] = {
    class = "PRIEST",
    spec = "Holy",
    slots = {
        ["Neck"] = { 28822 },
        ["Shoulders"] = { 29054 },
        ["Back"] = { 28765 },
        ["Chest"] = { 29049, 29050 },
        ["Wrist"] = { 28511 },
        ["Hands"] = { 28508 },
        ["Waist"] = { 28652 },
        ["Legs"] = { 28742 },
        ["Feet"] = { 28663 },
        ["Rings"] = { 28763, 32385, 29290, 28790, 28661 },
        ["Trinkets"] = { 28823, 28590, 29376 },
        ["Main Hand"] = { 28771, 28782 },
        ["Twohand"] = { 28782 },
        ["Ranged"] = { 28588 },
    }
}

BiSGearCheckDB_TMB["PriestShadow"] = {
    class = "PRIEST",
    spec = "Shadow",
    slots = {
        ["Head"] = { 28804, 24266 },
        ["Neck"] = { 30666 },
        ["Shoulders"] = { 21869 },
        ["Back"] = { 28570 },
        ["Chest"] = { 21871 },
        ["Wrist"] = { 28515, 30684 },
        ["Hands"] = { 28780, 28507 },
        ["Waist"] = { 28799, 30675 },
        ["Legs"] = { 28594, 24262 },
        ["Feet"] = { 21870 },
        ["Rings"] = { 28753, 28793, 32385 },
        ["Trinkets"] = { 28789, 29370 },
        ["Main Hand"] = { 28770 },
        ["Offhand"] = { 29272 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_TMB["RogueAssassination"] = {
    class = "ROGUE",
    spec = "Assassination",
    slots = {
        ["Head"] = { 29044 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29045 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27531 },
        ["Waist"] = { 29247, 28828 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28649 },
        ["Trinkets"] = { 28830, 28579, 29383 },
        ["Main Hand"] = { 28572, 28768 },
        ["Offhand"] = { 28772, 28572, 28768 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB["RogueCombat"] = {
    class = "ROGUE",
    spec = "Combat",
    slots = {
        ["Head"] = { 29044, 30146 },
        ["Neck"] = { 29381, 28509 },
        ["Shoulders"] = { 29047, 27797, 30149 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29045, 30101 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27531, 30145 },
        ["Waist"] = { 28828, 29247, 30106 },
        ["Legs"] = { 28741, 29046, 30148 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28649, 29997 },
        ["Trinkets"] = { 28830, 29383, 21670, 28288, 23206 },
        ["Main Hand"] = { 28729, 28189 },
        ["Offhand"] = { 28729, 28772, 28189, 32027 },
        ["Ranged"] = { 28772, 29152, 29949 },
    }
}

BiSGearCheckDB_TMB["RogueSubtlety"] = {
    class = "ROGUE",
    spec = "Subtlety",
    slots = {
        ["Head"] = { 29044 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27797 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29045 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27531 },
        ["Waist"] = { 29247, 28750 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28649, 28757 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28438, 28189, 28768, 28729, 32837 },
        ["Offhand"] = { 28772, 28189, 28768, 28729, 32838 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB["ShamanElemental"] = {
    class = "SHAMAN",
    spec = "Elemental",
    slots = {
        ["Head"] = { 29035, 29028 },
        ["Neck"] = { 28762 },
        ["Shoulders"] = { 29037 },
        ["Back"] = { 28797, 28570 },
        ["Chest"] = { 29033, 29519 },
        ["Wrist"] = { 29521 },
        ["Hands"] = { 28780, 29034, 28520, 28507 },
        ["Waist"] = { 28799, 29520 },
        ["Legs"] = { 24262, 28751, 28594 },
        ["Feet"] = { 28517, 28810, 28752 },
        ["Rings"] = { 30667, 28753, 28763 },
        ["Trinkets"] = { 28785, 29370, 28789 },
        ["Main Hand"] = { 28770, 28522 },
        ["Offhand"] = { 29268 },
        ["Ranged"] = { 28248, 28523 },
    }
}

BiSGearCheckDB_TMB["ShamanEnhancement"] = {
    class = "SHAMAN",
    spec = "Enhancement",
    slots = {
        ["Head"] = { 29040, 28804 },
        ["Neck"] = { 28509, 29381 },
        ["Shoulders"] = { 29043, 29031 },
        ["Back"] = { 28672, 24259, 28797 },
        ["Chest"] = { 29038, 29029, 28601 },
        ["Wrist"] = { 28514 },
        ["Hands"] = { 28776, 30644, 29039 },
        ["Waist"] = { 28828, 28799 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545, 28746 },
        ["Rings"] = { 28757, 28649, 32385 },
        ["Trinkets"] = { 28830, 29383, 19406, 28823, 28789 },
        ["Main Hand"] = { 28767, 28657 },
        ["Offhand"] = { 29458, 28781 },
        ["Ranged"] = { 27815 },
    }
}

BiSGearCheckDB_TMB["ShamanRestoration"] = {
    class = "SHAMAN",
    spec = "Restoration",
    slots = {
        ["Head"] = { 29028 },
        ["Neck"] = { 28609, 28822 },
        ["Shoulders"] = { 29031 },
        ["Back"] = { 28765 },
        ["Chest"] = { 29029 },
        ["Wrist"] = { 28503 },
        ["Hands"] = { 28520 },
        ["Waist"] = { 28567, 28655 },
        ["Legs"] = { 28751 },
        ["Feet"] = { 28752 },
        ["Rings"] = { 28763, 28790, 32385 },
        ["Trinkets"] = { 28590, 29376, 28823, 28830 },
        ["Main Hand"] = { 28771 },
        ["Offhand"] = { 29458 },
        ["Ranged"] = { 28523 },
    }
}

BiSGearCheckDB_TMB["WarlockAffliction"] = {
    class = "WARLOCK",
    spec = "Affliction",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28530, 28762 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 28964 },
        ["Hands"] = { 28968 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 28966 },
        ["Rings"] = { 28793, 28753, 32385 },
        ["Trinkets"] = { 28789, 29370 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 28783 },
    }
}

BiSGearCheckDB_TMB["WarlockDemonology"] = {
    class = "WARLOCK",
    spec = "Demonology",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28530, 28762 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 28964 },
        ["Wrist"] = { 28515 },
        ["Hands"] = { 28968 },
        ["Waist"] = { 28799, 24256 },
        ["Legs"] = { 28966 },
        ["Feet"] = { 28517, 28585 },
        ["Rings"] = { 28793, 32385, 28753 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 28783 },
    }
}

BiSGearCheckDB_TMB["WarlockDestruction"] = {
    class = "WARLOCK",
    spec = "Destruction",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28762, 28530 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 28964, 30107 },
        ["Wrist"] = { 29918 },
        ["Hands"] = { 28968 },
        ["Waist"] = { 28799, 30064 },
        ["Feet"] = { 28517, 30050 },
        ["Rings"] = { 28753, 32385, 28793, 30109 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 28783, 29982 },
    }
}

BiSGearCheckDB_TMB["WarriorArms"] = {
    class = "WARRIOR",
    spec = "Arms",
    slots = {
        ["Head"] = { 29021 },
        ["Neck"] = { 28745 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 28777, 28672 },
        ["Chest"] = { 29019 },
        ["Wrist"] = { 28795 },
        ["Hands"] = { 28824 },
        ["Waist"] = { 28779 },
        ["Legs"] = { 28741, 29022 },
        ["Feet"] = { 28608 },
        ["Rings"] = { 28757, 28730 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28729, 28773, 28573 },
        ["Offhand"] = { 28772, 28729, 28825 },
        ["Twohand"] = { 28773, 28573 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB["WarriorFury"] = {
    class = "WARRIOR",
    spec = "Fury",
    slots = {
        ["Head"] = { 29021 },
        ["Neck"] = { 28745, 28244, 29381 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 28777, 24259, 28672, 28660, 28377 },
        ["Chest"] = { 29019 },
        ["Wrist"] = { 28795, 28381 },
        ["Hands"] = { 28824, 30644 },
        ["Waist"] = { 28779, 28385 },
        ["Legs"] = { 28741, 29022, 28621 },
        ["Feet"] = { 28608, 28383 },
        ["Rings"] = { 28757, 28730, 30834, 29279 },
        ["Trinkets"] = { 28830, 29383, 28121 },
        ["Main Hand"] = { 28729, 28438, 28749 },
        ["Offhand"] = { 28729, 28772, 28825, 28749 },
        ["Ranged"] = { 28772, 28826, 30279 },
    }
}

BiSGearCheckDB_TMB["WarriorProtection"] = {
    class = "WARRIOR",
    spec = "Protection",
    slots = {
        ["Head"] = { 29011 },
        ["Neck"] = { 28516, 28509 },
        ["Shoulders"] = { 29023, 29016 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29012 },
        ["Wrist"] = { 28502 },
        ["Hands"] = { 28518, 30644 },
        ["Waist"] = { 28566, 28779 },
        ["Legs"] = { 28621 },
        ["Feet"] = { 28747, 28608 },
        ["Rings"] = { 30834 },
        ["Trinkets"] = { 28579, 28830 },
        ["Main Hand"] = { 28749 },
        ["Offhand"] = { 28825, 28749 },
        ["Ranged"] = { 28826 },
    }
}

