-- BiSGearCheck Data_EPWeights.lua
-- EP stat weights per spec for gear scoring
-- Auto-generated by scripts/build_ep_weights.py
-- Sources: WoWSims TBC defaults, EJ, community Pawn scales

BiSGearCheckEPWeights = {
    ["DruidBalance"] = {
        weights = {3,0.54,4,0.1,5,1.0,7,1.0,11,1.0,14,0.81,15,0.84,16,1.29},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 4,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.54, Spi=0.1, SP=1.0, ArcSP=1.0, NatSP=1.0, SpHit=0.81, SpCrit=0.84, SpHaste=1.29
    ["DruidFeralDPS"] = {
        weights = {0,2.27,1,3.5,18,1.0,19,3.2,20,2.37,21,1.36,22,0.47,23,3.2,41,1.0},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=2.27, Agi=3.5, AP=1.0, MHit=3.2, MCrit=2.37, MHaste=1.36, ArPen=0.47, Exp=3.2, FeralAP=1.0
    ["DruidFeralTank"] = {
        weights = {0,2.0,1,2.5,2,1.5,18,1.0,19,2.0,20,1.5,23,2.5,27,0.05,29,0.8,32,1.2,34,0.5,41,1.0},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=2.0, Agi=2.5, Sta=1.5, AP=1.0, MHit=2.0, MCrit=1.5, Exp=2.5, Armor=0.05, Def=0.8, Dodge=1.2, Resil=0.5, FeralAP=1.0
    ["DruidRestoration"] = {
        weights = {3,0.55,4,0.45,5,0.5,6,1.0,13,1.4,15,0.35,16,0.6},
        hitType = "spell",
        baseMiss = 0,
        talentHit = 0,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.55, Spi=0.45, SP=0.5, HP=1.0, MP5=1.4, SpCrit=0.35, SpHaste=0.6
    ["HunterBM"] = {
        weights = {0,0.15,1,2.5,3,0.2,18,1.0,19,1.8,20,2.3,21,1.97,22,0.4,28,1.0},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=0.15, Agi=2.5, Int=0.2, AP=1.0, MHit=1.8, MCrit=2.3, MHaste=1.97, ArPen=0.4, RAP=1.0
    ["HunterMM"] = {
        weights = {0,0.15,1,2.7,3,0.2,18,1.0,19,2.0,20,2.5,21,1.8,22,0.45,28,1.0},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=0.15, Agi=2.7, Int=0.2, AP=1.0, MHit=2.0, MCrit=2.5, MHaste=1.8, ArPen=0.45, RAP=1.0
    ["HunterSV"] = {
        weights = {0,0.15,1,3.0,3,0.25,18,1.0,19,2.0,20,2.2,21,1.6,22,0.35,28,1.0},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 3,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=0.15, Agi=3.0, Int=0.25, AP=1.0, MHit=2.0, MCrit=2.2, MHaste=1.6, ArPen=0.35, RAP=1.0
    ["MageArcane"] = {
        weights = {3,0.4,4,0.05,5,1.0,7,1.0,14,0.9,15,0.65,16,1.1},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 6,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.4, Spi=0.05, SP=1.0, ArcSP=1.0, SpHit=0.9, SpCrit=0.65, SpHaste=1.1
    ["MageFire"] = {
        weights = {3,0.35,4,0.05,5,1.0,8,1.0,14,0.85,15,0.75,16,1.2},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 3,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.35, Spi=0.05, SP=1.0, FireSP=1.0, SpHit=0.85, SpCrit=0.75, SpHaste=1.2
    ["MageFrost"] = {
        weights = {3,0.35,4,0.05,5,1.0,9,1.0,14,0.85,15,0.6,16,0.9},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 3,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.35, Spi=0.05, SP=1.0, FrostSP=1.0, SpHit=0.85, SpCrit=0.6, SpHaste=0.9
    ["PaladinHoly"] = {
        weights = {3,0.6,4,0.1,5,0.5,6,1.0,13,1.5,15,0.4,16,0.5,20,0.3},
        hitType = "spell",
        baseMiss = 0,
        talentHit = 0,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.6, Spi=0.1, SP=0.5, HP=1.0, MP5=1.5, SpCrit=0.4, SpHaste=0.5, MCrit=0.3
    ["PaladinProtection"] = {
        weights = {0,0.33,1,0.6,2,1.0,5,0.67,14,0.67,15,0.21,18,1.0,19,0.06,20,0.28,21,0.67,23,0.67,27,0.05,29,0.8,30,0.35,31,0.59,32,0.7,33,0.58,34,0.19},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=0.33, Agi=0.6, Sta=1.0, SP=0.67, SpHit=0.67, SpCrit=0.21, AP=1.0, MHit=0.06, MCrit=0.28, MHaste=0.67, Exp=0.67, Armor=0.05, Def=0.8, Block=0.35, BV=0.59, Dodge=0.7, Parry=0.58, Resil=0.19
    ["PaladinRetribution"] = {
        weights = {0,2.42,1,1.88,5,0.35,18,1.0,19,1.98,20,1.98,21,3.27,22,0.24,23,4.7},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=2.42, Agi=1.88, SP=0.35, AP=1.0, MHit=1.98, MCrit=1.98, MHaste=3.27, ArPen=0.24, Exp=4.7
    ["PriestHoly"] = {
        weights = {3,0.65,4,0.5,5,0.5,6,1.0,13,1.5,15,0.4,16,0.55},
        hitType = "spell",
        baseMiss = 0,
        talentHit = 0,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.65, Spi=0.5, SP=0.5, HP=1.0, MP5=1.5, SpCrit=0.4, SpHaste=0.55
    ["PriestShadow"] = {
        weights = {3,0.05,4,0.11,5,1.0,12,1.0,14,1.0,15,0.163,16,1.0},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 10,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.05, Spi=0.11, SP=1.0, ShadSP=1.0, SpHit=1.0, SpCrit=0.163, SpHaste=1.0
    ["RogueAssassination"] = {
        weights = {0,1.1,1,2.8,18,1.0,19,2.5,20,2.2,21,1.8,22,0.5,23,3.0},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=1.1, Agi=2.8, AP=1.0, MHit=2.5, MCrit=2.2, MHaste=1.8, ArPen=0.5, Exp=3.0
    ["RogueCombat"] = {
        weights = {0,1.1,1,2.5,18,1.0,19,2.3,20,2.0,21,2.0,22,0.55,23,3.2},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 5,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=1.1, Agi=2.5, AP=1.0, MHit=2.3, MCrit=2.0, MHaste=2.0, ArPen=0.55, Exp=3.2
    ["RogueSubtlety"] = {
        weights = {0,1.0,1,2.6,18,1.0,19,2.4,20,2.1,21,1.5,22,0.4,23,2.8},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=1.0, Agi=2.6, AP=1.0, MHit=2.4, MCrit=2.1, MHaste=1.5, ArPen=0.4, Exp=2.8
    ["ShamanElemental"] = {
        weights = {3,0.33,5,1.0,11,1.0,13,0.08,14,0.9,15,0.78,16,1.25},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 3,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.33, SP=1.0, NatSP=1.0, MP5=0.08, SpHit=0.9, SpCrit=0.78, SpHaste=1.25
    ["ShamanEnhancement"] = {
        weights = {0,2.2,1,1.317,3,0.078,5,0.433,11,0.216,15,0.283,18,1.0,19,1.665,20,1.357,21,1.944,23,2.871},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 3,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=2.2, Agi=1.317, Int=0.078, SP=0.433, NatSP=0.216, SpCrit=0.283, AP=1.0, MHit=1.665, MCrit=1.357, MHaste=1.944, Exp=2.871
    ["ShamanRestoration"] = {
        weights = {3,0.6,4,0.1,5,0.5,6,1.0,13,1.6,15,0.35,16,0.5},
        hitType = "spell",
        baseMiss = 0,
        talentHit = 0,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.6, Spi=0.1, SP=0.5, HP=1.0, MP5=1.6, SpCrit=0.35, SpHaste=0.5
    ["WarlockAffliction"] = {
        weights = {3,0.4,4,0.1,5,1.0,12,1.0,14,0.9,15,0.6,16,1.0},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 10,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.4, Spi=0.1, SP=1.0, ShadSP=1.0, SpHit=0.9, SpCrit=0.6, SpHaste=1.0
    ["WarlockDemonology"] = {
        weights = {3,0.45,4,0.1,5,1.0,8,1.0,12,1.0,14,0.85,15,0.7,16,1.1},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 0,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.45, Spi=0.1, SP=1.0, FireSP=1.0, ShadSP=1.0, SpHit=0.85, SpCrit=0.7, SpHaste=1.1
    ["WarlockDestruction"] = {
        weights = {3,0.4,4,0.1,5,1.0,8,1.0,12,1.0,14,0.9,15,0.8,16,1.2},
        hitType = "spell",
        baseMiss = 16,
        talentHit = 0,
        hitStatIndex = 14,
        hitRatingPerPct = 12.62,
    }, -- Int=0.4, Spi=0.1, SP=1.0, FireSP=1.0, ShadSP=1.0, SpHit=0.9, SpCrit=0.8, SpHaste=1.2
    ["WarriorArms"] = {
        weights = {0,2.2,1,1.6,18,1.0,19,2.5,20,2.0,21,1.5,22,0.6,23,3.5},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=2.2, Agi=1.6, AP=1.0, MHit=2.5, MCrit=2.0, MHaste=1.5, ArPen=0.6, Exp=3.5
    ["WarriorFury"] = {
        weights = {0,2.3,1,1.8,18,1.0,19,2.5,20,2.2,21,1.8,22,0.55,23,3.8},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 3,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=2.3, Agi=1.8, AP=1.0, MHit=2.5, MCrit=2.2, MHaste=1.8, ArPen=0.55, Exp=3.8
    ["WarriorProtection"] = {
        weights = {0,1.5,1,1.2,2,1.8,18,1.0,19,1.5,20,1.0,23,2.5,27,0.05,29,1.0,30,0.6,31,0.8,32,0.9,33,0.85,34,0.3},
        hitType = "melee",
        baseMiss = 9,
        talentHit = 0,
        hitStatIndex = 19,
        hitRatingPerPct = 15.77,
    }, -- Str=1.5, Agi=1.2, Sta=1.8, AP=1.0, MHit=1.5, MCrit=1.0, Exp=2.5, Armor=0.05, Def=1.0, Block=0.6, BV=0.8, Dodge=0.9, Parry=0.85, Resil=0.3
}
