-- BiSGearCheck Data_TMB_Phase2.lua
-- ThatsMyBis top wishlisted items - Phase 2 (community aggregate data)
-- P2 items ranked first per slot, P1 items fill remaining slots
-- Auto-generated by Playwright TMB scraper + phase split

BiSGearCheckDB_TMB_Phase2 = {}

BiSGearCheckDB_TMB_Phase2["DruidBalance"] = {
    class = "DRUID",
    spec = "Balance",
    slots = {
        ["Head"] = { 29093 },
        ["Neck"] = { 28530, 28762 },
        ["Shoulders"] = { 29095 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 29091 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 28594 },
        ["Feet"] = { 28517, 28585 },
        ["Rings"] = { 28753, 28793 },
        ["Trinkets"] = { 28789, 29370, 27683 },
        ["Main Hand"] = { 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 27518 },
    }
}

BiSGearCheckDB_TMB_Phase2["DruidFeralDPS"] = {
    class = "DRUID",
    spec = "Feral DPS",
    slots = {
        ["Head"] = { 29098 },
        ["Neck"] = { 28509 },
        ["Shoulders"] = { 29100 },
        ["Back"] = { 28660, 28672 },
        ["Chest"] = { 29096 },
        ["Waist"] = { 28828, 28750 },
        ["Legs"] = { 28741, 29099 },
        ["Feet"] = { 28545, 30674 },
        ["Rings"] = { 28649, 28792 },
        ["Trinkets"] = { 28830, 28579 },
        ["Twohand"] = { 28658 },
    }
}

BiSGearCheckDB_TMB_Phase2["DruidFeralTank"] = {
    class = "DRUID",
    spec = "Feral Tank",
    slots = {
        ["Head"] = { 29098 },
        ["Neck"] = { 28509 },
        ["Shoulders"] = { 29100 },
        ["Back"] = { 28660, 28672 },
        ["Chest"] = { 29096 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 29099, 28741 },
        ["Feet"] = { 30674, 28545 },
        ["Rings"] = { 28792, 28649, 29279 },
        ["Trinkets"] = { 28830, 28579 },
        ["Twohand"] = { 28658 },
        ["Ranged"] = { 23198 },
    }
}

BiSGearCheckDB_TMB_Phase2["DruidRestoration"] = {
    class = "DRUID",
    spec = "Restoration",
    slots = {
        ["Head"] = { 29086, 28803 },
        ["Neck"] = { 28822, 28609 },
        ["Shoulders"] = { 29089 },
        ["Back"] = { 28765 },
        ["Chest"] = { 29087 },
        ["Wrist"] = { 28511 },
        ["Waist"] = { 28655 },
        ["Legs"] = { 28591 },
        ["Feet"] = { 28752 },
        ["Rings"] = { 28763, 28790 },
        ["Trinkets"] = { 29376, 28590, 28823 },
        ["Main Hand"] = { 28771 },
        ["Twohand"] = { 28782 },
        ["Ranged"] = { 27886 },
    }
}

BiSGearCheckDB_TMB_Phase2["HunterBM"] = {
    class = "HUNTER",
    spec = "Beast Mastery",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 28509, 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 28672, 28777, 24259 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Waist"] = { 28828, 28750 },
        ["Legs"] = { 28741, 30739 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28649, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28572 },
        ["Twohand"] = { 28587 },
        ["Ranged"] = { 30105, 28772 },
    }
}

BiSGearCheckDB_TMB_Phase2["HunterMM"] = {
    class = "HUNTER",
    spec = "Marksmanship",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 28509, 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 28672, 28777 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 28741, 30739 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28649, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28572, 28524 },
        ["Twohand"] = { 28587 },
        ["Ranged"] = { 28772, 28581 },
    }
}

BiSGearCheckDB_TMB_Phase2["HunterSV"] = {
    class = "HUNTER",
    spec = "Survival",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 28343 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 29994, 28672 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 30686 },
        ["Waist"] = { 28750, 28828, 30677 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545, 28746 },
        ["Rings"] = { 28791, 28649, 28757 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28572 },
        ["Twohand"] = { 28587 },
        ["Ranged"] = { 30105, 28772 },
    }
}

BiSGearCheckDB_TMB_Phase2["MageArcane"] = {
    class = "MAGE",
    spec = "Arcane",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28762, 28530 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28797, 28766 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 29078, 28594 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28753, 28793, 29287 },
        ["Trinkets"] = { 28785, 29370, 28789 },
        ["Main Hand"] = { 28802, 28770 },
        ["Ranged"] = { 28783, 28673 },
    }
}

BiSGearCheckDB_TMB_Phase2["MageFire"] = {
    class = "MAGE",
    spec = "Fire",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28762, 28530 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766, 28797 },
        ["Wrist"] = { 28515 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 29078 },
        ["Feet"] = { 28517, 28585 },
        ["Rings"] = { 28793, 28753 },
        ["Trinkets"] = { 29370 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 28783 },
    }
}

BiSGearCheckDB_TMB_Phase2["MageFrost"] = {
    class = "MAGE",
    spec = "Frost",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28530, 28762 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766, 28797 },
        ["Wrist"] = { 28515 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 29078 },
        ["Feet"] = { 28517, 28585 },
        ["Rings"] = { 28793, 28753 },
        ["Trinkets"] = { 28789, 28785 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28783, 28673 },
    }
}

BiSGearCheckDB_TMB_Phase2["PaladinHoly"] = {
    class = "PALADIN",
    spec = "Holy",
    slots = {
        ["Head"] = { 29061 },
        ["Neck"] = { 28822, 28609 },
        ["Shoulders"] = { 29064 },
        ["Back"] = { 28765 },
        ["Chest"] = { 29062 },
        ["Wrist"] = { 28512 },
        ["Waist"] = { 28733 },
        ["Legs"] = { 28748 },
        ["Feet"] = { 28569, 28752 },
        ["Rings"] = { 28790, 28763 },
        ["Trinkets"] = { 28590, 28727, 29376 },
        ["Main Hand"] = { 28771 },
        ["Offhand"] = { 29458 },
        ["Ranged"] = { 28592 },
    }
}

BiSGearCheckDB_TMB_Phase2["PaladinProtection"] = {
    class = "PALADIN",
    spec = "Protection",
    slots = {
        ["Head"] = { 29068 },
        ["Neck"] = { 28516 },
        ["Shoulders"] = { 29070 },
        ["Back"] = { 28766, 27804 },
        ["Chest"] = { 29066 },
        ["Wrist"] = { 28502 },
        ["Waist"] = { 28566 },
        ["Legs"] = { 29069, 28621 },
        ["Feet"] = { 30641 },
        ["Rings"] = { 28675 },
        ["Trinkets"] = { 28789, 28528 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 28825 },
        ["Ranged"] = { 29388 },
    }
}

BiSGearCheckDB_TMB_Phase2["PaladinRetribution"] = {
    class = "PALADIN",
    spec = "Retribution",
    slots = {
        ["Head"] = { 29073 },
        ["Neck"] = { 28745, 28509 },
        ["Shoulders"] = { 29075 },
        ["Back"] = { 28777, 28672 },
        ["Chest"] = { 29071 },
        ["Wrist"] = { 28795 },
        ["Waist"] = { 30106, 28779 },
        ["Feet"] = { 28608, 28545 },
        ["Rings"] = { 28757, 28730, 30834 },
        ["Trinkets"] = { 28830, 29383 },
        ["Twohand"] = { 28800, 28773 },
        ["Ranged"] = { 27484 },
    }
}

BiSGearCheckDB_TMB_Phase2["PriestHoly"] = {
    class = "PRIEST",
    spec = "Holy",
    slots = {
        ["Head"] = { 29049 },
        ["Neck"] = { 28822 },
        ["Shoulders"] = { 29054 },
        ["Back"] = { 28765 },
        ["Chest"] = { 29050 },
        ["Wrist"] = { 28511 },
        ["Waist"] = { 28652 },
        ["Legs"] = { 28742 },
        ["Feet"] = { 28663 },
        ["Rings"] = { 28763, 29290, 28790, 28661 },
        ["Trinkets"] = { 28823, 28590, 29376 },
        ["Main Hand"] = { 28771 },
        ["Twohand"] = { 28782 },
        ["Ranged"] = { 28588 },
    }
}

BiSGearCheckDB_TMB_Phase2["PriestShadow"] = {
    class = "PRIEST",
    spec = "Shadow",
    slots = {
        ["Head"] = { 28804, 24266 },
        ["Neck"] = { 30666 },
        ["Shoulders"] = { 21869 },
        ["Back"] = { 28570 },
        ["Chest"] = { 21871, 29056 },
        ["Wrist"] = { 28515, 30684 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 28594, 24262 },
        ["Feet"] = { 21870 },
        ["Rings"] = { 28753, 28793 },
        ["Trinkets"] = { 28789, 29370 },
        ["Main Hand"] = { 28770 },
        ["Offhand"] = { 29272 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_TMB_Phase2["RogueAssassination"] = {
    class = "ROGUE",
    spec = "Assassination",
    slots = {
        ["Head"] = { 29044 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29045 },
        ["Wrist"] = { 29246 },
        ["Waist"] = { 29247, 28828 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28649 },
        ["Trinkets"] = { 28830, 29383, 28579 },
        ["Main Hand"] = { 28572, 28768 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB_Phase2["RogueCombat"] = {
    class = "ROGUE",
    spec = "Combat",
    slots = {
        ["Head"] = { 29044 },
        ["Neck"] = { 29381, 28509 },
        ["Shoulders"] = { 29047, 27797 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29045 },
        ["Wrist"] = { 29246 },
        ["Waist"] = { 28828, 29247 },
        ["Legs"] = { 28741, 29046 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28649 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28729, 28189 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB_Phase2["RogueSubtlety"] = {
    class = "ROGUE",
    spec = "Subtlety",
    slots = {
        ["Head"] = { 30146, 29044 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 30149 },
        ["Back"] = { 28672 },
        ["Chest"] = { 30101, 29045 },
        ["Waist"] = { 30106, 30040, 29247, 28750 },
        ["Legs"] = { 30148, 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 30052, 29997, 28649, 28757 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 30082, 28438 },
        ["Ranged"] = { 29949, 28772 },
    }
}

BiSGearCheckDB_TMB_Phase2["ShamanElemental"] = {
    class = "SHAMAN",
    spec = "Elemental",
    slots = {
        ["Head"] = { 29035 },
        ["Neck"] = { 28762 },
        ["Shoulders"] = { 29037 },
        ["Back"] = { 28797 },
        ["Chest"] = { 29033, 29519 },
        ["Wrist"] = { 29918, 29521 },
        ["Waist"] = { 28799, 29520 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517, 28810 },
        ["Rings"] = { 30667, 28753 },
        ["Trinkets"] = { 28785, 29370 },
        ["Main Hand"] = { 28770 },
        ["Offhand"] = { 29268 },
        ["Ranged"] = { 28248 },
    }
}

BiSGearCheckDB_TMB_Phase2["ShamanEnhancement"] = {
    class = "SHAMAN",
    spec = "Enhancement",
    slots = {
        ["Head"] = { 29040 },
        ["Neck"] = { 28509, 29381 },
        ["Shoulders"] = { 29043 },
        ["Back"] = { 28672, 24259 },
        ["Chest"] = { 29038 },
        ["Wrist"] = { 28514 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545, 28746 },
        ["Rings"] = { 28757, 28649 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28767, 28657 },
        ["Ranged"] = { 27815 },
    }
}

BiSGearCheckDB_TMB_Phase2["ShamanRestoration"] = {
    class = "SHAMAN",
    spec = "Restoration",
    slots = {
        ["Head"] = { 29028 },
        ["Neck"] = { 28609, 28822 },
        ["Shoulders"] = { 29031 },
        ["Back"] = { 28765 },
        ["Chest"] = { 29029 },
        ["Wrist"] = { 28503 },
        ["Waist"] = { 28567, 28655 },
        ["Legs"] = { 28751 },
        ["Feet"] = { 28752 },
        ["Rings"] = { 28763, 28790 },
        ["Trinkets"] = { 28590, 29376, 28823 },
        ["Main Hand"] = { 28771 },
        ["Offhand"] = { 29458 },
        ["Ranged"] = { 28523 },
    }
}

BiSGearCheckDB_TMB_Phase2["WarlockAffliction"] = {
    class = "WARLOCK",
    spec = "Affliction",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28530, 28762 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 28964 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 28966 },
        ["Rings"] = { 28793, 28753 },
        ["Trinkets"] = { 28789, 29370 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 28783 },
    }
}

BiSGearCheckDB_TMB_Phase2["WarlockDemonology"] = {
    class = "WARLOCK",
    spec = "Demonology",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28530, 28762 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 28964 },
        ["Wrist"] = { 28515 },
        ["Waist"] = { 28799, 24256 },
        ["Legs"] = { 28966 },
        ["Feet"] = { 28517, 28585 },
        ["Rings"] = { 28793, 28753 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 28783 },
    }
}

BiSGearCheckDB_TMB_Phase2["WarlockDestruction"] = {
    class = "WARLOCK",
    spec = "Destruction",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28762, 28530 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766, 28797 },
        ["Chest"] = { 28964 },
        ["Waist"] = { 28799 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28753, 28793 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28802, 28770 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673, 28783 },
    }
}

BiSGearCheckDB_TMB_Phase2["WarriorArms"] = {
    class = "WARRIOR",
    spec = "Arms",
    slots = {
        ["Head"] = { 29021 },
        ["Neck"] = { 28745 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 28777, 28672, 24259 },
        ["Chest"] = { 29019 },
        ["Wrist"] = { 28795 },
        ["Waist"] = { 28779 },
        ["Legs"] = { 28741, 29022 },
        ["Feet"] = { 28608 },
        ["Rings"] = { 28757, 28730 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28729 },
        ["Offhand"] = { 28825 },
        ["Twohand"] = { 28773 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB_Phase2["WarriorFury"] = {
    class = "WARRIOR",
    spec = "Fury",
    slots = {
        ["Head"] = { 29021 },
        ["Neck"] = { 28745 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 28777, 24259 },
        ["Chest"] = { 29019 },
        ["Wrist"] = { 28795 },
        ["Waist"] = { 30106, 28779 },
        ["Legs"] = { 28741, 29022 },
        ["Feet"] = { 28608 },
        ["Rings"] = { 29997, 28757, 28730 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28729, 28438 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_TMB_Phase2["WarriorProtection"] = {
    class = "WARRIOR",
    spec = "Protection",
    slots = {
        ["Head"] = { 29011 },
        ["Neck"] = { 28516, 28509 },
        ["Shoulders"] = { 29023, 29016 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29012 },
        ["Wrist"] = { 28502, 28795 },
        ["Waist"] = { 28566, 28779 },
        ["Legs"] = { 28621 },
        ["Feet"] = { 28747 },
        ["Rings"] = { 30834 },
        ["Trinkets"] = { 28579, 28830 },
        ["Main Hand"] = { 28749 },
        ["Offhand"] = { 28825 },
        ["Ranged"] = { 28826 },
    }
}

