-- BiSGearCheck Data_WoWSims_Phase2.lua
-- WoWSims TBC simulation-derived BiS data (Phase 2)
-- Auto-generated by scripts/extract_wowsims.py

BiSGearCheckDB_WoWSims_Phase2 = {}

BiSGearCheckDB_WoWSims_Phase2["DruidBalance"] = {
    class = "DRUID",
    spec = "Balance",
    slots = {
        ["Head"] = { 30233 },
        ["Neck"] = { 30015 },
        ["Shoulders"] = { 30235 },
        ["Back"] = { 28797 },
        ["Chest"] = { 30231 },
        ["Wrist"] = { 29918 },
        ["Hands"] = { 30232 },
        ["Waist"] = { 30038 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 30067 },
        ["Rings"] = { 28753, 29302 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 29988 },
        ["Offhand"] = { 32387 },
    }
}

BiSGearCheckDB_WoWSims_Phase2["DruidFeralDPS"] = {
    class = "DRUID",
    spec = "Feral DPS",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["DruidFeralTank"] = {
    class = "DRUID",
    spec = "Feral Tank",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["DruidRestoration"] = {
    class = "DRUID",
    spec = "Restoration",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["HunterBM"] = {
    class = "HUNTER",
    spec = "Beast Mastery",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["HunterMM"] = {
    class = "HUNTER",
    spec = "Marksmanship",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["HunterSV"] = {
    class = "HUNTER",
    spec = "Survival",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["MageArcane"] = {
    class = "MAGE",
    spec = "Arcane",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["MageFire"] = {
    class = "MAGE",
    spec = "Fire",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["MageFrost"] = {
    class = "MAGE",
    spec = "Frost",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["PaladinHoly"] = {
    class = "PALADIN",
    spec = "Holy",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["PaladinProtection"] = {
    class = "PALADIN",
    spec = "Protection",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["PaladinRetribution"] = {
    class = "PALADIN",
    spec = "Retribution",
    slots = {
        ["Head"] = { 32235 },
        ["Neck"] = { 30022 },
        ["Shoulders"] = { 30055 },
        ["Back"] = { 33590 },
        ["Chest"] = { 30905 },
        ["Wrist"] = { 32574 },
        ["Hands"] = { 29947 },
        ["Waist"] = { 30106 },
        ["Legs"] = { 30900 },
        ["Feet"] = { 32366 },
        ["Rings"] = { 32526, 30834 },
        ["Trinkets"] = { 33831, 28830 },
        ["Main Hand"] = { 32332 },
        ["Offhand"] = { 27484 },
    }
}

BiSGearCheckDB_WoWSims_Phase2["PriestHoly"] = {
    class = "PRIEST",
    spec = "Holy",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["PriestShadow"] = {
    class = "PRIEST",
    spec = "Shadow",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["RogueAssassination"] = {
    class = "ROGUE",
    spec = "Assassination",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["RogueCombat"] = {
    class = "ROGUE",
    spec = "Combat",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["RogueSubtlety"] = {
    class = "ROGUE",
    spec = "Subtlety",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["ShamanElemental"] = {
    class = "SHAMAN",
    spec = "Elemental",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["ShamanEnhancement"] = {
    class = "SHAMAN",
    spec = "Enhancement",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["ShamanRestoration"] = {
    class = "SHAMAN",
    spec = "Restoration",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["WarlockAffliction"] = {
    class = "WARLOCK",
    spec = "Affliction",
    slots = {
        ["Head"] = { 31051 },
        ["Neck"] = { 33281 },
        ["Shoulders"] = { 31054 },
        ["Back"] = { 32524 },
        ["Chest"] = { 30107 },
        ["Wrist"] = { 32586 },
        ["Hands"] = { 31050 },
        ["Waist"] = { 30888 },
        ["Legs"] = { 31053 },
        ["Feet"] = { 32239 },
        ["Rings"] = { 32527, 33497 },
        ["Trinkets"] = { 32483, 33829 },
        ["Main Hand"] = { 32374 },
        ["Ranged"] = { 33192 },
    }
}

BiSGearCheckDB_WoWSims_Phase2["WarlockDemonology"] = {
    class = "WARLOCK",
    spec = "Demonology",
    slots = {
        ["Head"] = { 31051 },
        ["Neck"] = { 33281 },
        ["Shoulders"] = { 31054 },
        ["Back"] = { 32524 },
        ["Chest"] = { 30107 },
        ["Wrist"] = { 32586 },
        ["Hands"] = { 31050 },
        ["Waist"] = { 30888 },
        ["Legs"] = { 31053 },
        ["Feet"] = { 32239 },
        ["Rings"] = { 32527, 33497 },
        ["Trinkets"] = { 32483, 33829 },
        ["Main Hand"] = { 32374 },
        ["Ranged"] = { 33192 },
    }
}

BiSGearCheckDB_WoWSims_Phase2["WarlockDestruction"] = {
    class = "WARLOCK",
    spec = "Destruction",
    slots = {
        ["Head"] = { 31051 },
        ["Neck"] = { 33281 },
        ["Shoulders"] = { 31054 },
        ["Back"] = { 32524 },
        ["Chest"] = { 30107 },
        ["Wrist"] = { 32586 },
        ["Hands"] = { 31050 },
        ["Waist"] = { 30888 },
        ["Legs"] = { 31053 },
        ["Feet"] = { 32239 },
        ["Rings"] = { 32527, 33497 },
        ["Trinkets"] = { 32483, 33829 },
        ["Main Hand"] = { 32374 },
        ["Ranged"] = { 33192 },
    }
}

BiSGearCheckDB_WoWSims_Phase2["WarriorArms"] = {
    class = "WARRIOR",
    spec = "Arms",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["WarriorFury"] = {
    class = "WARRIOR",
    spec = "Fury",
    slots = {
    }
}

BiSGearCheckDB_WoWSims_Phase2["WarriorProtection"] = {
    class = "WARRIOR",
    spec = "Protection",
    slots = {
    }
}

