-- BiSGearCheck Data_WoWSims.lua
-- WoWSims TBC simulation-derived BiS data
-- Auto-generated by scripts/extract_wowsims.py

BiSGearCheckDB_WoWSims = {}

BiSGearCheckDB_WoWSims["DruidBalance"] = {
    class = "DRUID",
    spec = "Balance",
    slots = {
        ["Head"] = { 29093 },
        ["Neck"] = { 28762 },
        ["Shoulders"] = { 29095 },
        ["Back"] = { 28766 },
        ["Chest"] = { 21848 },
        ["Wrist"] = { 24250 },
        ["Hands"] = { 21847 },
        ["Waist"] = { 21846 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28753, 28793 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28770 },
        ["Offhand"] = { 29271 },
        ["Ranged"] = { 27518 },
    }
}

BiSGearCheckDB_WoWSims["DruidFeralDPS"] = {
    class = "DRUID",
    spec = "Feral DPS",
    slots = {
        ["Head"] = { 8345 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 29100 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29096 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 28506 },
        ["Waist"] = { 28750 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28649, 30834 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28658 },
        ["Offhand"] = { 29390 },
    }
}

BiSGearCheckDB_WoWSims["DruidFeralTank"] = {
    class = "DRUID",
    spec = "Feral Tank",
    slots = {
        ["Head"] = { 29098 },
        ["Neck"] = { 28509 },
        ["Shoulders"] = { 29100 },
        ["Back"] = { 28660 },
        ["Chest"] = { 29096 },
        ["Wrist"] = { 28978 },
        ["Hands"] = { 29097 },
        ["Waist"] = { 28986 },
        ["Legs"] = { 29099 },
        ["Feet"] = { 30674 },
        ["Rings"] = { 29279, 28792 },
        ["Trinkets"] = { 28830, 23836 },
        ["Main Hand"] = { 28476 },
        ["Offhand"] = { 23198 },
    }
}

BiSGearCheckDB_WoWSims["DruidRestoration"] = {
    class = "DRUID",
    spec = "Restoration",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["HunterBM"] = {
    class = "HUNTER",
    spec = "Beast Mastery",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 24259 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27474 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 30739 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28435 },
        ["Offhand"] = { 28772 },
    }
}

BiSGearCheckDB_WoWSims["HunterMM"] = {
    class = "HUNTER",
    spec = "Marksmanship",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 24259 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27474 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 30739 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28435 },
        ["Offhand"] = { 28772 },
    }
}

BiSGearCheckDB_WoWSims["HunterSV"] = {
    class = "HUNTER",
    spec = "Survival",
    slots = {
        ["Head"] = { 28275 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27801 },
        ["Back"] = { 24259 },
        ["Chest"] = { 28228 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27474 },
        ["Waist"] = { 28828 },
        ["Legs"] = { 30739 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28791 },
        ["Trinkets"] = { 28830, 29383 },
        ["Main Hand"] = { 28435 },
        ["Offhand"] = { 28772 },
    }
}

BiSGearCheckDB_WoWSims["MageArcane"] = {
    class = "MAGE",
    spec = "Arcane",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28134 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766 },
        ["Chest"] = { 21848 },
        ["Wrist"] = { 28411 },
        ["Hands"] = { 21847 },
        ["Waist"] = { 21846 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28793, 29172 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 29270 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["MageFire"] = {
    class = "MAGE",
    spec = "Fire",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28134 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766 },
        ["Chest"] = { 21848 },
        ["Wrist"] = { 28411 },
        ["Hands"] = { 21847 },
        ["Waist"] = { 21846 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28793, 29172 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 29270 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["MageFrost"] = {
    class = "MAGE",
    spec = "Frost",
    slots = {
        ["Head"] = { 29076 },
        ["Neck"] = { 28134 },
        ["Shoulders"] = { 29079 },
        ["Back"] = { 28766 },
        ["Chest"] = { 21848 },
        ["Wrist"] = { 28411 },
        ["Hands"] = { 21847 },
        ["Waist"] = { 21846 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28793, 29172 },
        ["Trinkets"] = { 29370, 27683 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 29270 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["PaladinHoly"] = {
    class = "PALADIN",
    spec = "Holy",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["PaladinProtection"] = {
    class = "PALADIN",
    spec = "Protection",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["PaladinRetribution"] = {
    class = "PALADIN",
    spec = "Retribution",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["PriestHoly"] = {
    class = "PRIEST",
    spec = "Holy",
    slots = {
        ["Head"] = { 24266 },
        ["Neck"] = { 28530 },
        ["Shoulders"] = { 29060 },
        ["Back"] = { 28766 },
        ["Chest"] = { 29056 },
        ["Wrist"] = { 24250 },
        ["Hands"] = { 30725 },
        ["Waist"] = { 24256 },
        ["Legs"] = { 30734 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 28793, 29172 },
        ["Trinkets"] = { 27683, 29370 },
        ["Main Hand"] = { 30723 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["PriestShadow"] = {
    class = "PRIEST",
    spec = "Shadow",
    slots = {
        ["Head"] = { 24266 },
        ["Neck"] = { 30666 },
        ["Shoulders"] = { 21869 },
        ["Back"] = { 28570 },
        ["Chest"] = { 21871 },
        ["Wrist"] = { 24250 },
        ["Hands"] = { 28507 },
        ["Waist"] = { 28799 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 21870 },
        ["Rings"] = { 29352, 28793 },
        ["Trinkets"] = { 28789, 29370 },
        ["Main Hand"] = { 28770 },
        ["Offhand"] = { 29272 },
        ["Ranged"] = { 29350 },
    }
}

BiSGearCheckDB_WoWSims["RogueAssassination"] = {
    class = "ROGUE",
    spec = "Assassination",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["RogueCombat"] = {
    class = "ROGUE",
    spec = "Combat",
    slots = {
        ["Head"] = { 29044 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 27797 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29045 },
        ["Wrist"] = { 29246 },
        ["Hands"] = { 27531 },
        ["Waist"] = { 29247 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28545 },
        ["Rings"] = { 28757, 28649 },
        ["Trinkets"] = { 29383, 28830 },
        ["Main Hand"] = { 28729, 28768 },
        ["Offhand"] = { 28189, 29182 },
        ["Ranged"] = { 28772 },
    }
}

BiSGearCheckDB_WoWSims["RogueSubtlety"] = {
    class = "ROGUE",
    spec = "Subtlety",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["ShamanElemental"] = {
    class = "SHAMAN",
    spec = "Elemental",
    slots = {
        ["Head"] = { 29035 },
        ["Neck"] = { 28762 },
        ["Shoulders"] = { 29037 },
        ["Back"] = { 28797 },
        ["Chest"] = { 29519 },
        ["Wrist"] = { 29521 },
        ["Hands"] = { 28780 },
        ["Waist"] = { 29520 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 28517 },
        ["Rings"] = { 30667, 28753 },
        ["Trinkets"] = { 29370, 28785 },
        ["Main Hand"] = { 28770 },
        ["Offhand"] = { 29273 },
        ["Ranged"] = { 28248 },
    }
}

BiSGearCheckDB_WoWSims["ShamanEnhancement"] = {
    class = "SHAMAN",
    spec = "Enhancement",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["ShamanRestoration"] = {
    class = "SHAMAN",
    spec = "Restoration",
    slots = {
    }
}

BiSGearCheckDB_WoWSims["WarlockAffliction"] = {
    class = "WARLOCK",
    spec = "Affliction",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28530 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766 },
        ["Chest"] = { 28964 },
        ["Wrist"] = { 24250 },
        ["Hands"] = { 28968 },
        ["Waist"] = { 24256 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 21870 },
        ["Rings"] = { 28793, 28753 },
        ["Trinkets"] = { 27683, 29370 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["WarlockDemonology"] = {
    class = "WARLOCK",
    spec = "Demonology",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28530 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766 },
        ["Chest"] = { 28964 },
        ["Wrist"] = { 24250 },
        ["Hands"] = { 28968 },
        ["Waist"] = { 24256 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 21870 },
        ["Rings"] = { 28793, 28753 },
        ["Trinkets"] = { 27683, 29370 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["WarlockDestruction"] = {
    class = "WARLOCK",
    spec = "Destruction",
    slots = {
        ["Head"] = { 28963 },
        ["Neck"] = { 28530 },
        ["Shoulders"] = { 28967 },
        ["Back"] = { 28766 },
        ["Chest"] = { 28964 },
        ["Wrist"] = { 24250 },
        ["Hands"] = { 28968 },
        ["Waist"] = { 24256 },
        ["Legs"] = { 24262 },
        ["Feet"] = { 21870 },
        ["Rings"] = { 28793, 28753 },
        ["Trinkets"] = { 27683, 29370 },
        ["Main Hand"] = { 28802 },
        ["Offhand"] = { 28734 },
        ["Ranged"] = { 28673 },
    }
}

BiSGearCheckDB_WoWSims["WarriorArms"] = {
    class = "WARRIOR",
    spec = "Arms",
    slots = {
        ["Head"] = { 29021 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 24259 },
        ["Chest"] = { 29019 },
        ["Wrist"] = { 28795 },
        ["Hands"] = { 28824 },
        ["Waist"] = { 28779 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28608 },
        ["Rings"] = { 28757, 30834 },
        ["Trinkets"] = { 29383, 28830 },
        ["Main Hand"] = { 28438 },
        ["Offhand"] = { 28729 },
        ["Ranged"] = { 30279 },
    }
}

BiSGearCheckDB_WoWSims["WarriorFury"] = {
    class = "WARRIOR",
    spec = "Fury",
    slots = {
        ["Head"] = { 29021 },
        ["Neck"] = { 29381 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 24259 },
        ["Chest"] = { 29019 },
        ["Wrist"] = { 28795 },
        ["Hands"] = { 28824 },
        ["Waist"] = { 28779 },
        ["Legs"] = { 28741 },
        ["Feet"] = { 28608 },
        ["Rings"] = { 28757, 30834 },
        ["Trinkets"] = { 29383, 28830 },
        ["Main Hand"] = { 28438 },
        ["Offhand"] = { 28729 },
        ["Ranged"] = { 30279 },
    }
}

BiSGearCheckDB_WoWSims["WarriorProtection"] = {
    class = "WARRIOR",
    spec = "Protection",
    slots = {
        ["Head"] = { 29011 },
        ["Neck"] = { 28244 },
        ["Shoulders"] = { 29023 },
        ["Back"] = { 28672 },
        ["Chest"] = { 29012 },
        ["Wrist"] = { 28996 },
        ["Hands"] = { 30644 },
        ["Waist"] = { 28995 },
        ["Legs"] = { 28621 },
        ["Feet"] = { 28747 },
        ["Rings"] = { 30834, 29279 },
        ["Trinkets"] = { 28121, 29387 },
        ["Main Hand"] = { 28749 },
        ["Offhand"] = { 28825 },
        ["Ranged"] = { 28826 },
    }
}

